baseurl = "https://ryanjennin.gs/"
languageCode = "en-us"
title = "ryan jennings"
publishDir = "server/public"
buildDrafts = false

## Enable comments by entering your Disqus shortname
disqusShortname = "arg3"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-28532156-1"
# Define the number of posts per page
paginate = 10
footnotereturnlinkcontents = "â†©"
theme = "coda"

[permalinks]
    post = "/:year/:month/:day/:slug"

[params]
    author = "Ryan Jennings"
    description = "a namespace for technical and musical musings"
    introURL = "/post"
    githubUsername = "ryjen"
    copyright  = "&copy; all rights reserved, ryan jennings"
    highlight = true
    highlightStyle = "solarized-dark"
    brandName = "ryan jennings"

[[menu.main]]
    name  = "blog"
    url   = "/post"
    identifier  = "rss"
    weight = 2

[[menu.main]]
    name  = "music"
    identifier  = "music"
    url   = "/music"
    weight = 3

[[menu.main]]
    name   = "doodles"
    identifier = "paint-brush"
    url    = "/doodles"
    weight = 4
    
[[menu.main]]
    name  = "things"
    identifier  = "object-ungroup"
    url   = "/things"
    weight = 5

[[menu.icons]]
    url = "/resume/"
    name = "file-o"
    weight = 1

[[menu.icons]]
    url = "mailto:ryan@coda.life"
    name = "envelope-o"
    weight = 2

[[menu.icons]]
    url = "https://github.com/ryjen/"
    name = "github"
    weight = 3


